// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {models} from '../models';

export function GetData():Promise<database.Data>;

export function GetSettings():Promise<models.Settings>;

export function OpenFolderDialog(arg1:string):Promise<string>;

export function SaveSettings(arg1:models.Settings):Promise<void>;
